fx_version 'adamant'
games { 'gta5' }

author 'ANTUNES'
description 'Karma Developments Graphics Overhaul - Lights Overhaul'
version '2.0.0'

this_is_a_map 'yes'

files {
	"stream/**/**/**/**/**/*.ytyp",
	"stream/**/**/**/**/**/*.ytd",
    "stream/**/**/**/**/**/*.ydr",
    "stream/**/**/**/**/**/*.ydd",
    "stream/**/**/**/**/**/*.ycd",
    "stream/**/**/**/**/**/*.ymap",
    "stream/**/**/**/**/**/*.ymf",
	
}


data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/waxbulbs.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/nve_volumecaster.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/laserlight.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/vu_sing_girls.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/v_sing_bulbs.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/vu_sing_unicorn.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/vu_sing_open.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/upnatom.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/traffic_messageboard.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/traffic_sings.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/showroom_leds.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/liquor_sing_boxes_overlay.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/liquor_sing_fwy.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/liquor_sing_text.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/liquor_sing.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/liquor_sing_letters.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/liquor_sing_open.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/liquor_sing_boxes.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/paletosing_bulbs.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/paletobar_lights.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/paletomotel_sing.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/diosysia_meta.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/mall_meta.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/city_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/casino_meta.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/sstorage_meta.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/hookies_meta.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/hood_sing.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/dashhound_meta.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/wind_ads.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/animation_stuff1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/lp_atlas2x1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/luckypluck_bulbs.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/luckypluck_bulbs2.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/sc1_14_sing.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/cs4_10_bar_sing.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/cs4_10_bar_sing_night.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/liquor_blaine_bulbs.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/liquor_blaine_sing.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/letons_neons.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/hospital_mtz_sing.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/nve_volumecaster_headlight.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/dinerupnatom_meta.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/caseys_meta.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/common_open3.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/common_247.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/common_tattoo.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/common_pizza.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/common_open2.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/common_tattoo_neon.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/common_open.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/common_atm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/common_coffee.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/common_barber.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/common_logger.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/city_lights.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/carwash_sing_handson.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/carwash_arrowsing_bulbs.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/carwash_slopes.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/burger_sing_neons.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/boathouse_sing.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/bishop_ufo.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/bahama_winows_neon.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/bahama_drink.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/bahama_logo.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/bahama_neons.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/chopshop_sing_bulbs.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/chopshop_sing_lcs.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/chopshop_sing_24auto.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/chopshop_sing_24auto_cs.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/arena_meta.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/**/**/**/**/ammu_sing.ytyp'

dependency '/assetpacks'