AddTextEntry("WEAPON_PP19", "PP-19")
AddTextEntry("WEAPON_AK74", "AK-74")
AddTextEntry("WEAPON_BEANBAG", "Beanbag Shotgun")
AddTextEntry("WEAPON_FNX", "FNX-45")
AddTextEntry("WEAPON_G17", "Glock 17")
AddTextEntry("weapon_glock19x2", "Glock 19X")
AddTextEntry("WEAPON_HK416B", "HK416B")
AddTextEntry("WEAPON_SNIPERRIFLE2", "Hunting Rifle")
AddTextEntry("WEAPON_MP9a", "MP9")
AddTextEntry("WEAPON_MPX", "MPX")
AddTextEntry("WEAPON_TASER", "Taser")
AddTextEntry("WEAPON_UZI", "UZI")
AddTextEntry("WEAPON_MINIUZI", "Mini UZI")
AddTextEntry("WEAPON_MP5", "MP5")
AddTextEntry("WEAPON_P320A", "P320a")
AddTextEntry("WEAPON_L5", "Desert Eagle L5")
AddTextEntry("WEAPON_FLASHBANG", "Flashbang")
AddTextEntry("WEAPON_G36", "G36")
AddTextEntry("WEAPON_G45", "Glock 45")
AddTextEntry("WEAPON_M45A1", "M45A1")
AddTextEntry("WEAPON_RPK16", "RPK16")
AddTextEntry("WEAPON_2011", "STI DVC 2011")
